name: saas_shinko
description: A new Flutter project.

publish_to: 'none' # Remove this line if you intend to publish this package.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.0
  uuid: ^4.4.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  flutter_masked_text2: ^0.9.0+1
  fl_chart: ^0.68.0
  pdf: ^3.10.4 # Para gerar PDFs
  printing: ^5.12.0 # Importante para abrir o PDF na web ou imprimir
  url_launcher: ^6.2.2 # Para abrir URLs, útil para PDF na web
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # OU ^5.0.0, use a versão que já estava antes, mas APENAS UMA VEZ!
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true